name: "Joshua Raichur"
description: "Joshua Raichur likes to make things."
author: "Joshua Raichur"
url: "http://joshuaraichur.com"
future: true
permalink: /:title
highlighter: pygments

# Includes and exculdes
exclude: [README.md, Rakefile, node_modules]

# Defaults
defaults:
  -
    values:
      layout: "default"
  -
    scope:
      path: "_posts"
    values:
      layout: "post"
  -
    scope:
      path: "_pages"
    values:
      layout: "page"


# Social
github_username: "raichur"
twitter_username: "joshuaraichur"
dribbble_username: "geek"
