name: "Joshua Raichur"
description: "Joshua Raichur likes to make things."
author: "Joshua Raichur"
url: "http://joshuaraichur.com"
future: true
exclude: [README.md, Rakefile, node_modules]
permalink: /:title
highlighter: pygments

# Social
github_username: "raichur"
twitter_username: "joshuaraichur"
dribbble_username: "geek"
